spring:
  datasource:
    url: jdbc:mysql://10.168.0.52:3306/testjpa
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      # \u66F4\u65B0\u6216\u8005\u521B\u5EFA\u6570\u636E\u5E93\u8868\u7ED3\u6784
      ddl-auto: update
    # \u5728\u63A7\u5236\u53F0\u663E\u793Asql
    show-sql: true